// ============================================
// BEYOND STICH — Seed Catalog (local source)
// ============================================
// NOTE: This is the LOCAL seed used before the database is connected.
// Do NOT import this file directly in pages/components. Always go through
// the data-access layer at `@/lib/data/products` so that swapping to the
// real database later is a one-file change. See that file for details.

// Shared pool of known-good apparel imagery so nothing renders broken.
const IMG = {
  gym1: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
  gym2: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80',
  coffee1: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
  neutral1: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
  dark1: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=800&q=80',
  neon1: 'https://images.unsplash.com/photo-1512327428889-607eeb19efe8?w=800&q=80',
  gamer1: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
  portrait1: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
};

const fullStock = [
  { size: 'S', stock: 8 },
  { size: 'M', stock: 14 },
  { size: 'L', stock: 12 },
  { size: 'XL', stock: 7 },
  { size: 'XXL', stock: 4 },
];

export const DUMMY_PRODUCTS = [
  {
    _id: 'p1',
    name: 'MIND OVER MATTER',
    slug: 'mind-over-matter',
    segment: 'GYM',
    price: 799,
    mrp: 1299,
    images: [IMG.gym1, IMG.gym2],
    sizes: [
      { size: 'S', stock: 5 },
      { size: 'M', stock: 12 },
      { size: 'L', stock: 1 },
      { size: 'XL', stock: 0 },
      { size: 'XXL', stock: 8 },
    ],
    colors: ['Black'],
    description:
      'When the weights get heavy, the mind takes over. Heavyweight 240 GSM cotton built for the hardest sessions.',
    material: '240 GSM Combed Cotton',
    fitType: 'Oversized',
    tags: ['new', 'trending'],
    averageRating: 4.8,
    reviewCount: 42,
    featured: true,
    createdAt: '2025-07-20',
  },
  {
    _id: 'p2',
    name: 'CAFFEINE DRIVEN',
    slug: 'caffeine-driven',
    segment: 'COFFEE',
    price: 899,
    mrp: 1499,
    images: [IMG.coffee1, IMG.neutral1],
    sizes: fullStock,
    colors: ['White', 'Mocha'],
    description:
      'Fuel for the thinkers and the creators. A minimal drop for those who start their day right.',
    material: '220 GSM Loop-Knit Cotton',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.5,
    reviewCount: 18,
    featured: false,
    createdAt: '2025-07-05',
  },
  {
    _id: 'p3',
    name: 'SILENT MOVES',
    slug: 'silent-moves',
    segment: 'MILLINIORE',
    price: 999,
    mrp: 1599,
    images: [IMG.neutral1, IMG.coffee1],
    sizes: [
      { size: 'S', stock: 0 },
      { size: 'M', stock: 3 },
      { size: 'L', stock: 7 },
      { size: 'XL', stock: 10 },
      { size: 'XXL', stock: 5 },
    ],
    colors: ['Black'],
    description:
      'Hustle in silence, let the success make the noise. Gold accent prints on premium dark cotton.',
    material: '240 GSM Cotton, Gold Foil Print',
    fitType: 'Super Oversized',
    tags: ['premium'],
    averageRating: 5.0,
    reviewCount: 9,
    featured: true,
    createdAt: '2025-07-18',
  },
  {
    _id: 'p4',
    name: 'NIGHT RIDER',
    slug: 'night-rider',
    segment: 'BIKE',
    price: 799,
    mrp: 1299,
    images: [IMG.dark1, IMG.gym1],
    sizes: fullStock,
    colors: ['Black', 'Grey'],
    description:
      'Built for the wind. Subtle reflective prints that catch the streetlights.',
    material: '240 GSM Cotton, Reflective Ink',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.2,
    reviewCount: 31,
    featured: false,
    createdAt: '2025-06-28',
  },
  {
    _id: 'p5',
    name: 'SYNTH WAVE',
    slug: 'synth-wave',
    segment: 'MUSIC',
    price: 849,
    mrp: 1399,
    images: [IMG.neon1, IMG.neutral1],
    sizes: [
      { size: 'M', stock: 12 },
      { size: 'L', stock: 10 },
      { size: 'XL', stock: 8 },
    ],
    colors: ['Black'],
    description:
      'Feel the 80s frequency. Neon aesthetic meant for the midnight drives.',
    material: '220 GSM Cotton, HD Print',
    fitType: 'Oversized',
    tags: ['trending'],
    averageRating: 4.9,
    reviewCount: 56,
    featured: true,
    createdAt: '2025-07-22',
  },
  {
    _id: 'p6',
    name: 'NO RESPAWNS',
    slug: 'no-respawns',
    segment: 'GAMER',
    price: 899,
    mrp: 1499,
    images: [IMG.gamer1, IMG.dark1],
    sizes: fullStock,
    colors: ['Black', 'Green'],
    description:
      'One life. Play it well. Featuring breathable cotton for those long sessions.',
    material: '240 GSM Breathable Cotton',
    fitType: 'Super Oversized',
    tags: [],
    averageRating: 4.7,
    reviewCount: 112,
    featured: false,
    createdAt: '2025-07-01',
  },
  {
    _id: 'p7',
    name: 'REDLINE',
    slug: 'redline',
    segment: 'CARS',
    price: 949,
    mrp: 1599,
    images: [IMG.dark1, IMG.gym2],
    sizes: fullStock,
    colors: ['Black', 'Red'],
    description:
      'Push it to the limit. Motorsport-inspired graphics for those who live at full throttle.',
    material: '240 GSM Cotton',
    fitType: 'Oversized',
    tags: ['new'],
    averageRating: 4.6,
    reviewCount: 27,
    featured: true,
    createdAt: '2025-07-23',
  },
  {
    _id: 'p8',
    name: 'ENDLESS SUMMER',
    slug: 'endless-summer',
    segment: 'SUMMER',
    price: 749,
    mrp: 1199,
    images: [IMG.neutral1, IMG.coffee1],
    sizes: fullStock,
    colors: ['Sand', 'White'],
    description:
      'Coastal energy in every thread. Lightweight cotton that breathes with the ocean breeze.',
    material: '180 GSM Airy Cotton',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.4,
    reviewCount: 15,
    featured: false,
    createdAt: '2025-06-20',
  },
  {
    _id: 'p9',
    name: 'BLOOM DIFFERENT',
    slug: 'bloom-different',
    segment: 'FLORAL',
    price: 899,
    mrp: 1499,
    images: [IMG.portrait1, IMG.neutral1],
    sizes: fullStock,
    colors: ['Off-White'],
    description:
      'Bold florals for bold men. Hand-illustrated botanical prints that refuse to blend in.',
    material: '220 GSM Cotton, Reactive Dye',
    fitType: 'Oversized',
    tags: ['trending'],
    averageRating: 4.7,
    reviewCount: 34,
    featured: false,
    createdAt: '2025-07-10',
  },
  {
    _id: 'p10',
    name: 'OVERTIME',
    slug: 'overtime',
    segment: 'SPORTS',
    price: 799,
    mrp: 1299,
    images: [IMG.gym1, IMG.gamer1],
    sizes: fullStock,
    colors: ['Navy', 'Black'],
    description:
      'From the field to the street. Athletic cut with a varsity attitude.',
    material: '240 GSM Cotton',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.3,
    reviewCount: 21,
    featured: false,
    createdAt: '2025-06-15',
  },
  {
    _id: 'p11',
    name: 'HEARTLESS',
    slug: 'heartless',
    segment: 'VALENTINE',
    price: 849,
    mrp: 1399,
    images: [IMG.portrait1, IMG.dark1],
    sizes: fullStock,
    colors: ['Black', 'Red'],
    description:
      'Love loud or not at all. A statement piece for the ones who wear their heart on their chest.',
    material: '240 GSM Cotton',
    fitType: 'Oversized',
    tags: ['new'],
    averageRating: 4.5,
    reviewCount: 12,
    featured: false,
    createdAt: '2025-07-19',
  },
  {
    _id: 'p12',
    name: 'WORDS HIT HARDER',
    slug: 'words-hit-harder',
    segment: 'TYPOGRAPHY',
    price: 699,
    mrp: 1199,
    images: [IMG.neutral1, IMG.gym2],
    sizes: fullStock,
    colors: ['White', 'Black'],
    description:
      'Pure text. Pure impact. Nothing else needed. Bold typographic statement in high-density print.',
    material: '220 GSM Cotton',
    fitType: 'Super Oversized',
    tags: ['trending'],
    averageRating: 4.8,
    reviewCount: 48,
    featured: true,
    createdAt: '2025-07-21',
  },
  {
    _id: 'p13',
    name: 'GLITCH IN THE SYSTEM',
    slug: 'glitch-in-the-system',
    segment: 'RANDOMS',
    price: 899,
    mrp: 1499,
    images: [IMG.gamer1, IMG.neon1],
    sizes: fullStock,
    colors: ['Black'],
    description:
      "Designs that don't fit a box — and that's the point. A wildcard drop for the unpredictable.",
    material: '240 GSM Cotton',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.4,
    reviewCount: 19,
    featured: false,
    createdAt: '2025-06-30',
  },
  {
    _id: 'p14',
    name: 'IRON DISCIPLINE',
    slug: 'iron-discipline',
    segment: 'GYM',
    price: 849,
    mrp: 1399,
    images: [IMG.gym2, IMG.gym1],
    sizes: fullStock,
    colors: ['Black', 'Charcoal'],
    description:
      'Discipline is doing it when you don’t feel like it. Built for the grind, print that won’t quit.',
    material: '240 GSM Combed Cotton',
    fitType: 'Super Oversized',
    tags: ['trending'],
    averageRating: 4.9,
    reviewCount: 73,
    featured: true,
    createdAt: '2025-07-24',
  },
  {
    _id: 'p15',
    name: 'LATE NIGHT LOOP',
    slug: 'late-night-loop',
    segment: 'MUSIC',
    price: 799,
    mrp: 1299,
    images: [IMG.neon1, IMG.dark1],
    sizes: fullStock,
    colors: ['Black'],
    description:
      'For the ones who chase the beat past midnight. Soundwave graphics that pulse.',
    material: '220 GSM Cotton',
    fitType: 'Oversized',
    tags: [],
    averageRating: 4.6,
    reviewCount: 29,
    featured: false,
    createdAt: '2025-07-08',
  },
  {
    _id: 'p16',
    name: 'ESPRESSO YOURSELF',
    slug: 'espresso-yourself',
    segment: 'COFFEE',
    price: 749,
    mrp: 1199,
    images: [IMG.coffee1, IMG.neutral1],
    sizes: fullStock,
    colors: ['Cream', 'Mocha'],
    description:
      'A little pun, a lot of caffeine. Soft-hand print on a relaxed everyday oversized fit.',
    material: '200 GSM Cotton',
    fitType: 'Oversized',
    tags: ['new'],
    averageRating: 4.5,
    reviewCount: 22,
    featured: false,
    createdAt: '2025-07-16',
  },
];

// ============================================
// Reviews — keyed by product _id
// ============================================
// A small library shared across products. In the DB phase this becomes a
// query against the Review collection filtered by productId.
const REVIEW_LIBRARY = [
  {
    id: 'r1',
    author: 'Rahul S.',
    rating: 5,
    date: '2 months ago',
    title: 'Crazy fit and quality',
    body: "The 240 GSM feels premium. The print quality is insane and hasn't faded after 5 washes. Definitely ordering more.",
    verified: true,
    image: IMG.portrait1,
  },
  {
    id: 'r2',
    author: 'Karan V.',
    rating: 5,
    date: '1 week ago',
    title: 'Best oversized tee',
    body: 'The drop shoulder is perfect. Fits exactly how I wanted it to. Packaging was also very premium.',
    verified: true,
  },
  {
    id: 'r3',
    author: 'Vikram M.',
    rating: 4,
    date: '3 days ago',
    title: 'Good, but stock runs out fast',
    body: 'Love the design and the material. Only giving 4 stars because the restock takes too long. Otherwise perfect.',
    verified: true,
  },
  {
    id: 'r4',
    author: 'Aditya R.',
    rating: 5,
    date: '3 weeks ago',
    title: 'Worth every rupee',
    body: 'Heavyweight and structured — sits exactly like the photos. Got two compliments the first day I wore it.',
    verified: true,
  },
];

// Deterministic per-product reviews so the same product always shows the same set.
export const DUMMY_REVIEWS = DUMMY_PRODUCTS.reduce((acc, product, i) => {
  const count = 2 + (i % 3); // 2–4 reviews
  acc[product._id] = REVIEW_LIBRARY.slice(0, count).map((r) => ({
    ...r,
    id: `${product._id}-${r.id}`,
  }));
  return acc;
}, {});
